export const HELLO_PANEL = "HELLO_PANEL";
export const PODCAST_EDITOR_PANEL = "PODCAST_EDITOR_PANEL";
export const EMOTIONS_MAP_PANEL = "EMOTIONS_MAP_PANEL";
export const CATEGORY_WALL_PANEL = "CATEGORY_WALL_PANEL";
